Update secret manager to fix NoClassDefFoundError (#51)
Add func to handle uncaught jvm exceptions with timbre
Catch Throwable instead of Exception to avoid uncaught exceptions when initializing secret manager
Bump version of software.amazon.awssdk/secretsmanager