Update secret manager to fix NoClassDefFoundError Add func to handle uncaught jvm exceptions with timbre catch Throwable instead of Exception to avoid uncaught exceptions when initializing secret manager